services:
  - type: web
    name: iphone-olx-generator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        value: <TU_WKLEJ_SWÓJ_KLUCZ>
